# Generated by Django 3.2.17 on 2023-04-27 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='parent_comment',
        ),
    ]
