# Generated by Django 3.2.17 on 2023-02-12 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_styles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(db_index=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('avatar', models.ImageField(upload_to='photos/avatars/%Y/%m/%d/')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(db_index=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.article')),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.comments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.users')),
            ],
        ),
    ]
